### ISSUE TITLE
Facebook authentication fails

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#106]
### When trying to authenticate using Facebook, this error shows up 
![image](https://user-images.githubusercontent.com/2399010/136919856-d76262a2-7c54-4870-b82e-ccc756420cd8.png)

### ...and then the following fail screen is as below: 

![image](https://user-images.githubusercontent.com/2399010/136919736-09924933-e43a-415b-8b4d-56073339b6fd.png)

**Comment by DeepakChakravarthy** [comment]
I Would Like to Work on this Issue sir 
and get More Explored in the Configuration of Oauth with Facebook Authentication

**Comment by tushar5526** [comment]
This is because we are trying to access `email` from `user_info` dictionary after authorization, but there is no `email` present in the dictionary. Work around would be to redirect to a page where we have a prompty to enter email.

https://community.auth0.com/t/auth0-facebook-login-email-issue-2/21408/8 

I don't think there is any solid fix for it. We can skip the email or ask the users their email

**Comment by tushar5526** [comment]
In the maintainer meet we discussed, setting up a new prompt to ask for email is not a good option because in OAuth2, auth providers has the responsibility of sending verified data if the user allows. 

I will look for other alternatives to Auth0 in the mean time and share them here. 

cc @kgashok @Pavithratrdev

**Comment by kgashok** [comment]
A lot of users have started using patreon (https://www.patreon.com/) as well. FWIW,

**Comment by tushar5526** [comment]
I tried different ways to hit the graph API using access tokens and get the email of a user, but some users' profiles just don't have any email associated with them. Either their emails are not verified or they used a mobile number to log in, but Facebook is not sending anything back.  

I don't think switching to other providers will solve this issue, I am thinking of either redirecting the user to a new prompt for email input or just assigning a random email value to the user something like "user+(time)@facebook.com". The cons of the second approach are that the user will not get an email notification. Let me know your thoughts on this. 

I will take a look at whether Auth0 has inbuilt support for Patreon.  

@Pavithratrdev @kgashok

**Comment by kgashok** [comment]
@tushar5526 @Pavithratrdev  How about integration with Mastodon? 

https://blog.medium.com/medium-embraces-mastodon-19dcb873eb11

**Comment by kgashok** [comment]
```
KeyError
KeyError: 'email'

Traceback (most recent call last)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/whitenoise/base.py", line 85, in __call__
return self.application(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
return self.app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/opt/saythanks.io/saythanks/core.py", line 555, in callback_handling
email = user_detail_info['email']
KeyError: 'email' 
```

is the new error that shows up now.

**Comment by kgashok** [comment]
Facebook authentication fails again. 

<img width="362" height="280" alt="Image" src="https://github.com/user-attachments/assets/65a7b475-1f40-407b-97a6-bc1cb8bda122" />

**Comment by jeffrey-theog06** [comment]
Sir, please assign me

**Comment by kgashok** [comment]
@jeffrey-theog06 All yours!

**Comment by jeffrey-theog06** [comment]
> [@jeffrey-theog06](https://github.com/jeffrey-theog06) All yours!

Thank you Sir! WIll start working on it
