### ISSUE TITLE
Error Auth0

### ISSUE THREAD

**Issue by aeonSolutions** [BlitzKraft/saythanks.io#229]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Desktop/saythanks.io (copy)/saythanks/core.py", line 328, in callback_handling
    nickname = user_detail_info['nickname']
KeyError: 'nickname'

**Comment by kgashok** [comment]
@aeonSolutions what is the ID you are trying to use?

**Comment by aeonSolutions** [comment]
Hi.
I tried connecting using Gmail. And then using github. 
My email is mtpsilva@gmail.com

**Comment by Pavithratrdev** [comment]
@aeonSolutions, @randomshell : Could you please check now?

**Comment by kgashok** [comment]
> @aeonSolutions, @randomshell : Could you please check now?

@Pavithratrdev can you please let us know how it was resolved?

**Comment by Pavithratrdev** [comment]
@kgashok: Auth0 key is expired, so we generated new key and placed it.

**Comment by javadnikbakht** [comment]
@Pavithratrdev I have this error when I try with my Github account with javadnikbakht@mail.com email address.

**Comment by Pavithratrdev** [comment]
@javadnikbakht : Please check now

**Comment by javadnikbakht** [comment]
> @javadnikbakht : Please check now

Thanks that's ok now.
